web:
  build: .
  container_name: plex_email
  ports:
    - "8383:80"
  expose:
    - "8383"
    - "80"
  restart: always
  volumes:
    - /opt/data/plexemail:/config
    - /opt/data/plex/config:/plex
